-- 1. Create the jobs table
CREATE TABLE IF NOT EXISTS public.jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    status text DEFAULT 'queued' NOT NULL,
    progress float8 DEFAULT 0 NOT NULL,
    message text,
    title text,
    file_path text,
    log text,
    url text NOT NULL
);

-- 2. Enable Row Level Security (RLS) for jobs
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy that allows all operations (Service Role will bypass this anyway)
CREATE POLICY "Allow service role full access" ON public.jobs
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- 4. Enable realtime for the jobs table
-- ALTER publication supabase_realtime ADD TABLE jobs;

-- 5. Storage RLS Policies (Run this after creating the 'downloads' bucket manually)
-- These allow the service role to manage objects in the 'downloads' bucket.

INSERT INTO storage.buckets (id, name, public) 
VALUES ('downloads', 'downloads', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Service Role Full Access" ON storage.objects
    FOR ALL 
    TO service_role
    USING (bucket_id = 'downloads')
    WITH CHECK (bucket_id = 'downloads');
